services:
  web:
    build: .
    command: uvicorn techsupport.asgi:application --host 0.0.0.0 --port 9000
    volumes:
      - media:/app/media
      - ./logs:/app/logs
    env_file:
      - .env.prod
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    user: celeryuser
    command: celery -A techsupport worker --loglevel=info
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.prod
    environment:
      - LANG=en_US.utf8
      - POSTGRES_MAX_CONNECTIONS=1000
    restart: always

  pgbouncer:
    image: edoburu/pgbouncer:latest
    env_file:
      - .env.prod
    ports:
      - "6432:6432"
    depends_on:
      - db

  redis:
    image: redis:alpine

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media:/app/media
    ports:
      - "8090:80"
    depends_on:
      - web

volumes:
  pgdata:
  media: