# Generated by Django 5.2.3 on 2025-06-18 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcategory',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название категории'),
        ),
    ]
