# Generated by Django 5.2.3 on 2025-06-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticketcategory_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_priorit_0bec9b_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
    ]
